baseURL = "http://example.org/"
languageCode = "en-us"
title = "cmh:apps"

paginate = 2

#[social]
  #twitter = "https://twitter.com/cmhApps"
  #instagram = "https://www.instagram.com/cmhapps/"
  #github = "https://github.com/forestryio/novela-hugo-starter"
  #linkedin= "https://www.linkedin.com/company/forestry.io"
  #dribbble = "#"
  #youtube = "#"

#[taxonomies]
#  tag = "tags"

#[params]
#  custom_css = ["css/myCSS.css"]
#  custom_css = ["css/myCSS.css", "css/bar.css"]


## sectionPagesMenu = "main"
[[menu.main]]
  name = "Terms"
  weight = 10
  url = "/posts/terms/"

[[menu.main]]
  name = "Privacy"
  weight = 20
  url = "/posts/privacy/"

[[menu.main]]
  name = "Tags"
  weight = 30
  url = "/tags/"

[[menu.main]]
  name = "Home"
  weight = 40
  url = "/"

## GDPR
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
